use super::actor::{Node, NodeServerHandle};
use crate::{
    names::Name, publisher::Publisher, publisher::PublisherAny, service_client::ServiceClient,
    subscriber::Subscriber, subscriber::SubscriberAny, NodeError, ServiceServer,
};
use roslibrust_common::{GraphProvider, ServiceFn, ServiceInfo, TopicInfo};
use std::time::Duration;

const SERVICE_TYPE_PROBE_TIMEOUT: Duration = Duration::from_secs(5);

/// Represents a handle to an underlying Node. NodeHandle's can be freely cloned, moved, copied, etc.
/// This class provides the user facing API for interacting with ROS.
/// The last node handle dropped shuts down the node.
#[derive(Clone)]
pub struct NodeHandle {
    inner: NodeServerHandle,
}

impl NodeHandle {
    // TODO builder, result, better error type
    /// Creates a new node, connects, and returns a handle to it
    /// It is idiomatic to call this once per process and treat the created node as singleton.
    /// The returned handle can be freely clone'd to create additional handles without creating additional connections.
    ///   - master_uri: Expects a fully resolved http uri for the master e.g. "http://my_host_name:11311"
    ///   - name: The name of the node, expected to be a valid ros name, all names are interpreted as 'global' in
    ///     ROS's namespace system. e.g. "my_node" -> "/my_node". "~my_node" is not supported
    pub async fn new(master_uri: &str, name: &str) -> Result<NodeHandle, NodeError> {
        let name = if name.starts_with("/") {
            Name::new(name)?
        } else {
            Name::new(format!("/{}", name))?
        };

        // Extra safety check that our name resolves now
        let _ = Name::new("test").unwrap().resolve_to_global(&name);

        // Follow ROS rules and determine our IP and hostname
        let (addr, hostname) = super::determine_addr(master_uri).await?;

        let node = Node::new(master_uri, &hostname, &name, addr).await?;
        let nh = NodeHandle { inner: node };

        Ok(nh)
    }

    /// This function may be removed...
    /// All node handles connect to a backend node server that actually handles the communication with ROS
    /// If this function returns false, the backend node server has shut down and this handle is invalid.
    /// This state should be unreachable by normal usage of the library.
    pub fn is_ok(&self) -> bool {
        // Check the atomic is_alive flag which is set to false during shutdown
        self.inner.is_alive()
    }

    /// Returns the network uri of XMLRPC server for the underlying node.
    /// This is address where ROS master communicates with the node.
    pub async fn get_client_uri(&self) -> Result<String, NodeError> {
        self.inner.get_client_uri().await
    }

    /// Create a new publisher any arbitrary message type.
    ///
    /// This function is intended to be used when a message definition was not available at compile time,
    /// such as when playing back data from a bag file.
    /// This function requires the text of the expanded message definition as would be produced by `gendeps --cat`.
    /// See <https://wiki.ros.org/roslib/gentools> for what this should like.
    /// Messages autogenerated with roslibrust_codegen will include this information in their DEFINITION constant.
    pub async fn advertise_any(
        &self,
        topic_name: &str,
        topic_type: &str,
        msg_definition: &str,
        queue_size: usize,
        latching: bool,
    ) -> Result<PublisherAny, NodeError> {
        let (sender, shutdown) = self
            .inner
            .register_publisher_any(topic_name, topic_type, msg_definition, queue_size, latching)
            .await?;
        Ok(PublisherAny::new(topic_name, sender, shutdown))
    }

    /// Create a new publisher for the given type.
    ///
    /// This function can be called multiple times to create multiple publishers for the same topic,
    /// however the FIRST call will establish the queue size and latching behavior for the topic.
    /// Subsequent calls will simply be given additional handles to the underlying publication.
    /// This behavior was chosen to mirror ROS1's API, however it is recommended to .clone() the returned publisher
    /// instead of calling this function multiple times.
    pub async fn advertise<T: roslibrust_common::RosMessageType>(
        &self,
        topic_name: &str,
        queue_size: usize,
        latching: bool,
    ) -> Result<Publisher<T>, NodeError> {
        let (sender, shutdown) = self
            .inner
            .register_publisher::<T>(topic_name, queue_size, latching)
            .await?;
        Ok(Publisher::new(topic_name, sender, shutdown))
    }

    /// Subscribe to a topic as a raw byte stream with no automatic deserialization.
    ///
    /// This will return the raw bytes of the message as received over the wire, not including the 4 byte overall length header.
    ///
    /// For publishing a string message "hello", the returned bytes would be:
    ///       [0x05, 0x00, 0x00, 0x00, // field length = 5
    ///        0x68, 0x65, 0x6c, 0x6c, 0x6f] // "hello"
    ///
    /// See: <https://wiki.ros.org/ROS/TCPROS> for more information on the wire format.
    pub async fn subscribe_any(
        &self,
        topic_name: &str,
        queue_size: usize,
    ) -> Result<SubscriberAny, NodeError> {
        let receiver = self
            .inner
            .register_subscriber::<roslibrust_common::ShapeShifter>(topic_name, queue_size)
            .await?;
        // Pass a weak reference so Subscriber doesn't keep the node alive
        let weak_node = self.inner.downgrade();
        Ok(SubscriberAny::new(
            receiver,
            topic_name.to_string(),
            weak_node,
        ))
    }

    /// Subscribe to a topic with automatic deserialization to the given type.
    ///
    /// This function will return an error if the rosmaster cannot be contacted.
    ///
    /// This function may be called multiple times on the same topic and each subscriber will receive a unique copy of the message.
    /// This function may be called multiple times on the same topic with different message types, deserialization will be attempted individually for them.
    pub async fn subscribe<T: roslibrust_common::RosMessageType>(
        &self,
        topic_name: &str,
        queue_size: usize,
    ) -> Result<Subscriber<T>, NodeError> {
        let receiver = self
            .inner
            .register_subscriber::<T>(topic_name, queue_size)
            .await?;
        // Pass a weak reference so Subscriber doesn't keep the node alive
        let weak_node = self.inner.downgrade();
        Ok(Subscriber::new(receiver, topic_name.to_string(), weak_node))
    }

    pub async fn service_client<T: roslibrust_common::RosServiceType>(
        &self,
        service_name: &str,
    ) -> Result<ServiceClient<T>, NodeError> {
        let service_name = Name::new(service_name)?;
        let sender = self
            .inner
            .register_service_client::<T>(&service_name)
            .await?;
        Ok(sender)
    }

    pub async fn advertise_service<T, F>(
        &self,
        service_name: &str,
        server: F,
    ) -> Result<ServiceServer, NodeError>
    where
        T: roslibrust_common::RosServiceType,
        F: ServiceFn<T>,
    {
        let service_name = Name::new(service_name)?;
        self.inner
            .register_service_server::<T, F>(&service_name, server)
            .await?;
        // Super important: Pass a Weak reference so ServiceServer doesn't keep the node alive
        let weak_node = self.inner.downgrade();
        Ok(ServiceServer::new(service_name, weak_node))
    }
}

impl GraphProvider for NodeHandle {
    async fn list_topics(&self) -> roslibrust_common::Result<Vec<TopicInfo>> {
        let client = {
            let node = self.inner.node.lock().await;
            node.client.clone()
        };

        let mut topics: Vec<_> = client
            .get_topic_types()
            .await
            .map_err(NodeError::from)?
            .into_iter()
            .map(|(name, type_name)| TopicInfo { name, type_name })
            .collect();
        topics.sort_by(|a, b| a.name.cmp(&b.name));
        Ok(topics)
    }

    async fn list_services(&self) -> roslibrust_common::Result<Vec<ServiceInfo>> {
        let (client, caller_id) = {
            let node = self.inner.node.lock().await;
            (node.client.clone(), node.node_name.to_string())
        };

        let service_names = client
            .get_system_state()
            .await
            .map_err(NodeError::from)?
            .service_names();

        // Spawn parallel tasks to probe service types for all services
        let probe_tasks: Vec<_> = service_names
            .into_iter()
            .map(|service_name| {
                let client = client.clone();
                let caller_id = caller_id.clone();
                tokio::spawn(async move {
                    let type_name = match tokio::time::timeout(SERVICE_TYPE_PROBE_TIMEOUT, async {
                        let service_uri = client.lookup_service(&service_name).await.ok()?;
                        Some(
                            crate::tcpros::probe_service_type(
                                &caller_id,
                                &service_name,
                                &service_uri,
                            )
                            .await,
                        )
                    })
                    .await
                    {
                        Ok(Some(type_name)) => type_name,
                        Ok(None) => {
                            log::warn!(
                                "Failed to look up service {service_name}. Returning empty type."
                            );
                            String::new()
                        }
                        Err(_) => {
                            log::warn!(
                                "Timed out probing service {service_name}. Returning empty type."
                            );
                            String::new()
                        }
                    };
                    ServiceInfo {
                        name: service_name,
                        type_name,
                    }
                })
            })
            .collect();

        // Collect results from all parallel tasks
        let mut services = Vec::with_capacity(probe_tasks.len());
        for task in probe_tasks {
            if let Ok(service_info) = task.await {
                services.push(service_info);
            }
        }

        services.sort_by(|a, b| a.name.cmp(&b.name));
        Ok(services)
    }
}
