//! This file shows how to correctly import files generated by build.rs:

// This macro trick correctly "imports" messages.rs into our crate
// This should only be invoked once in the crate and other locations can access the
// messages via `use`
include!(concat!(env!("OUT_DIR"), "/messages.rs"));

// Important to bring traits we need into scope from roslibrust
// In this case we need to the Publish trait in scope so we can access the .publish() function on our Publisher
use roslibrust::Publish;

// Writing a simple behavior that uses the generic traits from roslibrust
// and the generated types from the macro above.
async fn pub_counter(ros: impl roslibrust::Ros) {
    let publisher = ros
        .advertise::<std_msgs::Int16>("/example_counter")
        .await
        .unwrap();
    let mut counter = 0;
    loop {
        publisher
            .publish(&std_msgs::Int16 { data: counter })
            .await
            .unwrap();
        println!("Published {counter}");
        counter += 1;
        tokio::time::sleep(std::time::Duration::from_secs(1)).await;
    }
}

// Our actual "main" here doesn't do much, just shows the generate types
// are here and real.
#[tokio::main]
async fn main() {
    // Create a rosbridge client we can use
    let ros = roslibrust::rosbridge::ClientHandle::new("ws://localhost:9090")
        .await
        .unwrap();
    // Start our behavior while waiting for ctrl_c
    tokio::select! {
        _ = pub_counter(ros) => {}
        _ = tokio::signal::ctrl_c() => {}
    }
}

// Setup a test of our pub_counter behavior
#[cfg(test)]
mod test {
    use super::*;
    use roslibrust::{Subscribe, TopicProvider};

    #[tokio::test]
    async fn test_pub_counter() {
        // See: https://tokio.rs/tokio/topics/testing
        // This test doesn't take 1 second to run even thou it looks like it should!
        // Tokio simulates time in tests if you call pause()
        // This test takes 0.00s to run on a reasonable machine
        tokio::time::pause();
        let ros = roslibrust::mock::MockRos::new();

        // Subscribe to the topic we're publishing to
        let mut subscriber = ros
            .subscribe::<std_msgs::Int16>("/example_counter")
            .await
            .unwrap();

        // Start publishing in the background
        tokio::spawn(async move { pub_counter(ros).await });

        // Confirm we get the first message
        let msg = subscriber.next().await.unwrap();
        assert_eq!(msg.data, 0);

        // Confirm second message quickly times out
        let msg =
            tokio::time::timeout(tokio::time::Duration::from_millis(10), subscriber.next()).await;
        assert!(msg.is_err());

        // Wait a bit
        tokio::time::sleep(tokio::time::Duration::from_secs(1)).await;
        // Now get second message
        let msg = subscriber.next().await.unwrap();
        assert_eq!(msg.data, 1);
    }

    #[test]
    fn generated_registry_round_trips_backend_selected_json() {
        assert!(MESSAGE_REGISTRY
            .descriptors()
            .windows(2)
            .all(|pair| pair[0].ros_type_name < pair[1].ros_type_name));

        let descriptor = MESSAGE_REGISTRY
            .get("std_msgs/msg/Int16")
            .expect("generated registry should accept ROS2 type spelling");
        assert_eq!(descriptor.ros_type_name, "std_msgs/Int16");

        let message = MESSAGE_REGISTRY
            .message_from("std_msgs/Int16", &serde_json::json!({ "data": 42 }))
            .expect("valid dynamic message");
        let json = roslibrust::rosbridge::serialize_dynamic_message(&message)
            .expect("rosbridge JSON encoding");
        assert_eq!(json, br#"{"data":42}"#);
        let decoded_json = roslibrust::rosbridge::deserialize_dynamic_message(
            MESSAGE_REGISTRY
                .get("std_msgs::msg::dds_::Int16_")
                .expect("generated registry should accept DDS type spelling"),
            &json,
        )
        .expect("rosbridge JSON decoding");
        assert_eq!(decoded_json.value(), message.value());

        let malformed =
            roslibrust::rosbridge::deserialize_dynamic_message(descriptor, b"{").unwrap_err();
        assert!(matches!(
            malformed,
            roslibrust::DynamicMessageError::Deserialize { .. }
        ));
    }

    #[test]
    fn generated_registry_reports_lookup_and_validation_errors() {
        let unknown = MESSAGE_REGISTRY
            .from_value("not_a_package/Unknown", roslibrust::DynamicValue::Unit)
            .unwrap_err();
        assert!(matches!(
            unknown,
            roslibrust::DynamicMessageError::UnknownType(_)
        ));

        let invalid = MESSAGE_REGISTRY
            .from_value(
                "std_msgs/Int16",
                roslibrust::DynamicValue::Message(vec![roslibrust::DynamicField {
                    name: "data".to_owned(),
                    value: roslibrust::DynamicValue::String("not an integer".to_owned()),
                }]),
            )
            .unwrap_err();
        assert!(matches!(
            invalid,
            roslibrust::DynamicMessageError::InvalidValue { .. }
        ));
    }
}
