# Note: each job is in a separate workflow to support individual CI badges in the readme
name: Book 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  HOME: /root

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: rust:latest
    permissions:
      # Make sure we have permissions to push to rep
      contents: write
    defaults:
      run:
        # Default commands to running the book directory of our workspace
        working-directory: book
    steps:
      - uses: actions/checkout@v2

      # Install mdbook
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'
      
      # Test
      - run: mdbook test

      # Make sure build works
      - run: mdbook build

      # If we're on master deploy
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # TODO enable this once we're done testing
        # if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book