# Note: each job is in a separate workflow to support individual CI badges in the readme
name: Noetic

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  HOME: /root
  ROS_PACKAGE_PATH: /opt/ros/noetic/share
  # Coupled with our use of the test_log crate this should give us good CI output on failure
  RUST_LOG: debug

jobs:
  noetic:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container: carter12s/roslibrust-ci-noetic:rust_1_90
    timeout-minutes: 20
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Verify rust version
        run: source /root/.cargo/env; rustc --version
      - name: Lint
        run: source /root/.cargo/env; cargo fmt --all -- --check
      - name: Start rosbridge
        run: source /opt/ros/noetic/setup.bash; roslaunch rosbridge_server rosbridge_websocket.launch & disown; rosrun rosapi rosapi_node & sleep 1
      - name: Build and Test
        run: source /opt/ros/noetic/setup.bash; source /root/.cargo/env; RUST_LOG=debug cargo test --features ros1_test,all -- --test-threads 1